# Generated by Django 4.2.16 on 2024-10-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0002_remove_imagenes_url_imagenes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posters',
            name='url',
        ),
        migrations.AddField(
            model_name='posters',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='m/imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='m/imagenes/', verbose_name='Imagen'),
        ),
    ]
