# Generated by Django 4.2.16 on 2024-10-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0013_alter_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
