# Generated by Django 4.2.16 on 2024-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0014_videos_nombre_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/', verbose_name='Video'),
        ),
    ]
