# Generated by Django 4.2.16 on 2024-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0018_capitulos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulos',
            name='video',
        ),
        migrations.AddField(
            model_name='capitulos',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/1080p/', verbose_name='Video 1080p'),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/360p/', verbose_name='Video 360p'),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/480p/', verbose_name='Video 480p'),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/720p/', verbose_name='Video 720p'),
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
