# Generated by Django 4.2.16 on 2024-10-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='url',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
