# Generated by Django 4.2.16 on 2024-10-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0005_alter_imagenes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='url',
        ),
        migrations.AddField(
            model_name='banners',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='m/imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='status',
            field=models.CharField(default='new', max_length=25),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='medias',
            name='status',
            field=models.CharField(default='new', max_length=25),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
