# Generated by Django 4.2.16 on 2024-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0006_remove_banners_url_banners_imagen_capitulos_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covers',
            name='url',
        ),
        migrations.AddField(
            model_name='covers',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='m/imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
