# Generated by Django 4.2.16 on 2024-10-09 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0008_medias_ibm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='ibm',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='IBM'),
        ),
    ]
