# Generated by Django 4.2.16 on 2024-10-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0011_alter_capitulos_descripcion_alter_capitulos_ibm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='url',
        ),
    ]
