# Generated by Django 4.2.16 on 2024-10-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0012_remove_videos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/', verbose_name='Video'),
        ),
    ]
