# Generated by Django 4.2.16 on 2024-10-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0017_alter_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='m/videos/', verbose_name='Video'),
        ),
    ]
