# Generated by Django 4.2.16 on 2024-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0022_medias_genero_alter_medias_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medias',
            name='genero',
        ),
        migrations.AddField(
            model_name='medias',
            name='generos',
            field=models.ManyToManyField(related_name='medias', to='popview.generos', verbose_name='Géneros'),
        ),
        migrations.DeleteModel(
            name='Media_has_genero',
        ),
    ]
