# Generated by Django 4.2.16 on 2024-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0023_remove_medias_genero_medias_generos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='m/iconos/', verbose_name='Imagen'),
        ),
    ]
