# Generated by Django 4.2.16 on 2024-11-05 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popview', '0025_cuentas_groups_cuentas_is_active_cuentas_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
